### ISSUE TITLE
Project is active?

### ISSUE THREAD

**Issue by zoedsoupe** [kwrooijen/gungnir#39]
I would like to contribute and maintain this project, is it active?

**Comment by kwrooijen** [comment]
Hi there! Even though I'm not working much on this project, any pull requests / issues will be processed. I also have a branch for HoneySQL 2 which is practically ready. https://github.com/kwrooijen/gungnir/pull/38

So far I haven't found any issues in the branch. But I didn't think many people were using this library so I didn't bother to merge / release it yet. I'll try to do that somewhere this week.

If you have any questions feel free to open an issue or join the Gungnir channel on Slack.

**Comment by zoedsoupe** [comment]
Ok, I'm new to clojure community coming from Elixir so I'll try my best to solve those open issues! Do you mind if I try to "rewrite" your library only for study?

I'm glad to be able to contribute with this project!

**Comment by kwrooijen** [comment]
> Do you mind if I try to "rewrite" your library only for study?

That's completely fine!

**Comment by kwrooijen** [comment]
Just released version 0.0.2 which includes HoneySQL 2 as well as upgrading all the dependencies. I've also updated the [Gungnir Playground](https://github.com/kwrooijen/gungnir-playground) to work with the new version. I'll close this issue for now.
