### ISSUE TITLE
help with trivial issues

### ISSUE THREAD

**Issue by etolbakov** [kwrooijen/gungnir#6]
Hello Kevin,

Thank you for the great Gungnir presentation in the Dutch Clojure meetup.
The project is really great and inspiring.

Can you please advise if you are looking for any help or support for this project implementation (something small to start with) ?

Regards, Eugene

**Comment by kwrooijen** [comment]
Hi Eugene,

Thanks for the kind words, glad you liked it. Currently all the open issues are for discussions, so if you want to share your thoughts on them that would be great! I'll have a look if I can find some more tasks which needs to be done which are easy to pick up.

**Comment by etolbakov** [comment]
yeah, I've checked the list of open issues #4  attracted me the most.
I'm not familiar with Malli so if you could point me to the area which I can have a look at for inspiration that will be super helpful.
Also, could you please advise what is the preferred way of communication?
just in case my twitter handler "evtolbakov".

**Comment by kwrooijen** [comment]
There's a Gungnir Slack channel which you can join. As for Malli the best place would be to look at their README https://github.com/metosin/malli

I'll close this issue, we can continue the our conversation on Slack :)
